Updating SDK addresses for xDai support
1Hive/uniswap-sdk pull request #2
Opened 2020-10-13 00:03 UTC by crisog

The current SDK used on Honeyswap.org is published by me, this PR has the intention to publish the package under @1Hive org.

2020-10-13 21:20 UTC, onbjerg requested changes
I'd change the package name and version

2020-10-13 21:20 UTC, onbjerg commented on package.json
> +  "name": "uniswap-xdai-sdk",
```suggestion
  "name": "@1hive/honeyswap-sdk",
```

2020-10-13 21:20 UTC, onbjerg commented on package.json
> +  "version": "3.0.2a3",
```suggestion
  "version": "1.0.0",
```

2020-10-29 10:54 UTC, onbjerg commented
Hey @crisog, so sorry for the extremely delayed response. Is this the version of the library that Honeyswap is currently using? If so, I'd just merge it.

2021-02-17 18:25 UTC, lkngtn commented
@crisog can this be closed?

2021-02-17 18:29 UTC, crisog commented
> @crisog can this be closed?

I'm gonna merge this since this is the version being used right now.

2021-02-17 18:30 UTC, merged